const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const state = { hubUrl: "http://localhost:8080", odooUrl: "", contexts: [], selectedId: null, resource: null };

function escapeHtml(value = "") { const node = document.createElement("div"); node.textContent = String(value); return node.innerHTML; }
function toast(message, error = false) { const element = $("#toast"); $("b", element).textContent = message; element.classList.toggle("error", error); $("span", element).textContent = error ? "!" : "✓"; element.classList.add("show"); clearTimeout(toast.timer); toast.timer = setTimeout(() => element.classList.remove("show"), 2600); }
async function api(path, options = {}) { const response = await fetch(`${state.hubUrl}${path}`, { ...options, headers: { "Content-Type": "application/json" } }); if (!response.ok) { let detail = "Context Hub ne répond pas"; try { detail = (await response.json()).detail || detail; } catch (_) {} throw new Error(detail); } return response.status === 204 ? null : response.json(); }

async function loadSettings() { const stored = await chrome.storage.local.get({ hubUrl: "http://localhost:8080", odooUrl: "" }); state.hubUrl = stored.hubUrl.replace(/\/$/, ""); state.odooUrl = stored.odooUrl.replace(/\/$/, ""); $("#settings-form").elements.hubUrl.value = state.hubUrl; $("#settings-form").elements.odooUrl.value = state.odooUrl; $('[data-app="hub"]').dataset.url = state.hubUrl; const odoo = $('[data-app="odoo"]'); if (state.odooUrl) odoo.dataset.url = state.odooUrl; }
async function loadResource() { const result = await chrome.runtime.sendMessage({ type: "GET_ACTIVE_RESOURCE" }); state.resource = result?.resource || null; $("#resource-title").textContent = state.resource?.title || "Page non prise en charge"; $("#resource-url").textContent = state.resource?.url || "Ouvrez Gmail, Chat, Drive, Calendar ou Odoo."; $("#attach").disabled = !state.resource || !state.selectedId; }
async function loadContexts(query = "") { try { state.contexts = await api(`/api/v1/contexts${query ? `?q=${encodeURIComponent(query)}` : ""}`); renderContexts(); } catch (error) { $("#context-list").innerHTML = ""; $("#empty").classList.remove("hidden"); toast(`${error.message}. Vérifiez les paramètres de l’extension.`, true); } }
function renderContexts() { $("#context-list").innerHTML = state.contexts.map((context) => `<label class="context-item ${context.id === state.selectedId ? "selected" : ""}" data-id="${context.id}"><input type="radio" name="context" ${context.id === state.selectedId ? "checked" : ""}><span><strong>${escapeHtml(context.title)}</strong><small>${escapeHtml(context.summary || context.context_type)}</small></span><em>${context.resource_count}</em></label>`).join(""); $("#empty").classList.toggle("hidden", state.contexts.length !== 0); $$(".context-item").forEach((item) => item.addEventListener("click", () => { state.selectedId = item.dataset.id; renderContexts(); $("#attach").disabled = !state.resource; })); }
async function attach() { if (!state.resource || !state.selectedId) return; const button = $("#attach"); button.disabled = true; try { await api(`/api/v1/contexts/${state.selectedId}/resources`, { method: "POST", body: JSON.stringify(state.resource) }); toast("Ressource rattachée au contexte"); await loadContexts($("#context-search").value.trim()); } catch (error) { toast(error.message, true); } finally { button.disabled = false; } }
async function createContext(event) { event.preventDefault(); const form = event.currentTarget; const button = $("button[type=submit]", form); const values = Object.fromEntries(new FormData(form)); button.disabled = true; try { const context = await api("/api/v1/contexts", { method: "POST", body: JSON.stringify(values) }); state.selectedId = context.id; let attachError = null; if (state.resource) { try { await api(`/api/v1/contexts/${context.id}/resources`, { method: "POST", body: JSON.stringify(state.resource) }); } catch (error) { attachError = error; } } form.reset(); form.classList.add("hidden"); await loadContexts(); $("#attach").disabled = !state.resource; toast(attachError ? `Contexte créé, mais rattachement impossible : ${attachError.message}` : state.resource ? "Contexte créé et ressource rattachée" : "Contexte créé et sélectionné", Boolean(attachError)); } catch (error) { toast(`Création impossible : ${error.message}`, true); } finally { button.disabled = false; } }
async function navigateApp(event) { const url = event.currentTarget.dataset.url; if (!url) return showSettings(); const result = await chrome.runtime.sendMessage({ type: "NAVIGATE_APP", url }); if (!result?.ok) toast(result?.error || "Navigation impossible", true); }
function showSettings() { $("#attach-view").classList.add("hidden"); $("#settings-view").classList.remove("hidden"); }
function hideSettings() { $("#settings-view").classList.add("hidden"); $("#attach-view").classList.remove("hidden"); }
async function saveSettings(event) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); const origins = []; for (const value of [values.hubUrl, values.odooUrl].filter(Boolean)) { try { const url = new URL(value); origins.push(`${url.protocol}//${url.hostname}/*`); } catch (_) { return toast("URL invalide", true); } } const missing = []; for (const origin of origins) { if (!(await chrome.permissions.contains({ origins: [origin] }))) missing.push(origin); } if (missing.length) { const granted = await chrome.permissions.request({ origins: missing }); if (!granted) return toast("Autorisation de domaine refusée", true); } await chrome.storage.local.set(values); state.hubUrl = values.hubUrl.replace(/\/$/, ""); state.odooUrl = values.odooUrl.replace(/\/$/, ""); await chrome.runtime.sendMessage({ type: "REGISTER_HUB", url: state.hubUrl }); if (state.odooUrl) await chrome.runtime.sendMessage({ type: "REGISTER_ODOO", url: state.odooUrl }); await loadSettings(); toast("Paramètres enregistrés"); hideSettings(); await Promise.all([loadContexts(), loadResource()]); }

async function init() {
  await loadSettings();
  await Promise.all([loadContexts(), loadResource()]);
  $("#attach").addEventListener("click", attach);
  $("#refresh").addEventListener("click", () => Promise.all([loadContexts($("#context-search").value.trim()), loadResource()]));
  let timer; $("#context-search").addEventListener("input", (event) => { clearTimeout(timer); timer = setTimeout(() => loadContexts(event.target.value.trim()), 220); });
  $("#create-toggle").addEventListener("click", () => $("#create-form").classList.toggle("hidden"));
  $("#create-form").addEventListener("submit", createContext);
  $("#show-settings").addEventListener("click", showSettings); $("#back").addEventListener("click", hideSettings);
  $("#settings-form").addEventListener("submit", saveSettings);
  $$("#app-launcher button").forEach((button) => button.addEventListener("click", navigateApp));
  chrome.tabs.onActivated.addListener(() => setTimeout(loadResource, 250));
  chrome.tabs.onUpdated.addListener((_id, info) => { if (info.status === "complete") loadResource(); });
}
init();
